import { nanoid } from "nanoid";

const intLocalesID = nanoid();
const intOfiID = nanoid();
const arqIndID = nanoid();
const mobDisID = nanoid();

export const projectGroups = [
  {
    img: "https://res.cloudinary.com/dvuggm2if/image/upload/v1710398234/int.locales/1/nrr7mlhswy6fk8blxdto.png",
    imgHover:
      "https://res.cloudinary.com/dvuggm2if/image/upload/v1710398234/int.locales/3/bobrrzm32vpqgwuungjq.png",
    title: "Interior Locales",
    paramID: "interior-locales",
    id: intLocalesID,
    desc: "Lorem ipsum dolor sit amet consectetur adipiscing elit molestie sagittis, at inceptos a per magna semper ultrices dictumst cubilia, sed feugiat convallis auctor curabitur risus tristique etiam. Aliquet ultrices cursus sociis morbi diam mollis euismod bibendum",
  },
  {
    img: "https://images.unsplash.com/photo-1518756131217-31eb79b20e8f",
    imgHover:
      "https://images.unsplash.com/photo-1593795899768-947c4929449d?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=2672&q=80",

    title: "Interior Oficina",
    paramID: "interior-oficina",
    id: intOfiID,
    desc: "Lorem ipsum dolor sit amet consectetur adipiscing elit molestie sagittis, at inceptos a per magna semper ultrices dictumst cubilia, sed feugiat convallis auctor curabitur risus tristique etiam. Aliquet ultrices cursus sociis morbi diam mollis euismod bibendum",
  },
  {
    img: "https://res.cloudinary.com/dvuggm2if/image/upload/v1710398198/industrial/6/ve87hpucigwlspxbk5ea.png",
    imgHover:
      "https://res.cloudinary.com/dvuggm2if/image/upload/v1710398198/industrial/6/pxvqn0wkzrzcfhvgfdpf.png",

    title: "Arquitectura Industrial",
    paramID: "arquitectura-industrial",
    id: arqIndID,
    desc: "Lorem ipsum dolor sit amet consectetur adipiscing elit molestie sagittis, at inceptos a per magna semper ultrices dictumst cubilia, sed feugiat convallis auctor curabitur risus tristique etiam. Aliquet ultrices cursus sociis morbi diam mollis euismod bibendum",
  },
  {
    img: "https://images.unsplash.com/photo-1567306301408-9b74779a11af",
    imgHover:
      "https://images.unsplash.com/photo-1593795899768-947c4929449d?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=2672&q=80",

    title: "Mobiliario Diseño",
    paramID: "mobiliario-diseno",
    id: mobDisID,
    desc: "Lorem ipsum dolor sit amet consectetur adipiscing elit molestie sagittis, at inceptos a per magna semper ultrices dictumst cubilia, sed feugiat convallis auctor curabitur risus tristique etiam. Aliquet ultrices cursus sociis morbi diam mollis euismod bibendum",
  },
];
export const intLocalesProjects = [
{
    description: "Diseño nueva imagen | Nuevo modelo atención clientes",
    company: "Latam Travel",
    location: "Mall plaza Egaña, La Reina",
    area: "64 m2 aprox.",
    projectId: nanoid(),
    groupId: intLocalesID,
    img: [
      "https://res.cloudinary.com/dvuggm2if/image/upload/v1710398234/int.locales/1/nrr7mlhswy6fk8blxdto.png",
      "https://res.cloudinary.com/dvuggm2if/image/upload/v1710398234/int.locales/1/kkjsraa274rqonkwojy0.png",
      "https://res.cloudinary.com/dvuggm2if/image/upload/v1710398234/int.locales/1/q4orrp1tnea6a6f6qtgq.png",
      "https://res.cloudinary.com/dvuggm2if/image/upload/v1710398234/int.locales/1/o3zfpqxmfatnl7ljsaxl.png",
    ],
  },
  {
    description: "Diseño nueva imagen | Nuevo modelo atención clientes",
    company: "Latam Travel",
    location: "Av. Alemania 0558B",
    area: "145 m2",
    projectId: nanoid(),
    groupId: intLocalesID,
    img: [
      "https://res.cloudinary.com/dvuggm2if/image/upload/v1710398234/int.locales/2/cqxu91ge4odaqjbnomum.png",
      "https://res.cloudinary.com/dvuggm2if/image/upload/v1710398234/int.locales/2/bl2sd7j28gsxzoygrg8c.png",
      "https://res.cloudinary.com/dvuggm2if/image/upload/v1710398234/int.locales/2/mwrs57xrwo4ztulog026.png",
      "https://res.cloudinary.com/dvuggm2if/image/upload/v1710398234/int.locales/2/emkncrpqf8lltlyzgbm8.png",
      "https://res.cloudinary.com/dvuggm2if/image/upload/v1710398234/int.locales/2/xb1zcevswyahnl6ljr2d.png",
      "https://res.cloudinary.com/dvuggm2if/image/upload/v1710398234/int.locales/2/wm5rved7s6mnl4abac9z.png",
    ],
  },
  {
    description: "Diseño nueva imagen | Nuevo modelo atención clientes",
    company: "Latam Travel",
    location: "Av. Frei Montalva 0110, Punta Arenas",
    area: "90 m2",
    projectId: nanoid(),
    groupId: intLocalesID,
    img: [
      "https://res.cloudinary.com/dvuggm2if/image/upload/v1710398234/int.locales/3/bobrrzm32vpqgwuungjq.png",
      "https://res.cloudinary.com/dvuggm2if/image/upload/v1710398234/int.locales/3/nnpzc2shliyu6aib8nay.png",
      "https://res.cloudinary.com/dvuggm2if/image/upload/v1710398234/int.locales/3/lwihriplkgeu0a4jlzyj.png",
      "https://res.cloudinary.com/dvuggm2if/image/upload/v1710398234/int.locales/3/flinpaghraqhai77px2l.png",
      "https://res.cloudinary.com/dvuggm2if/image/upload/v1710398234/int.locales/3/js0hpjbm2juyfz8erpqs.png",
    ],
  },
  {
    description: "Diseño nueva imagen | Nuevo modelo atención clientes",
    company: "Latam Travel",
    location: "Mall Costanera Center, Santiago",
    area: "120 m2 aprox. c/u.",
    projectId: nanoid(),
    groupId: intLocalesID,
    img: [
      "https://res.cloudinary.com/dvuggm2if/image/upload/v1710398234/int.locales/4/gc0pxo5nayloh7xidqgq.png",
      "https://res.cloudinary.com/dvuggm2if/image/upload/v1710398234/int.locales/4/nlymgrofinimaumlguai.png",
      "https://res.cloudinary.com/dvuggm2if/image/upload/v1710398234/int.locales/4/jazgwfvdbo7t8e68xcbm.png",
      "https://res.cloudinary.com/dvuggm2if/image/upload/v1710398234/int.locales/4/cdsblkkd8gj5vs3o7u9q.png",
    ],
  },
  {
    description: "Tienda ícono Puerto Montt",
    company: "Entel S.A",
    location: "Benavente 550 local 3, piso 1 y 2, Puerto Montt",
    area: "440 m2 aprox.",
    projectId: nanoid(),
    groupId: intLocalesID,
    img: [
      "https://res.cloudinary.com/dvuggm2if/image/upload/v1710398234/int.locales/5/iaiamzfjl7yicbhu16cb.png",
      "https://res.cloudinary.com/dvuggm2if/image/upload/v1710398234/int.locales/5/wjbqazi2imnbyckna5mm.png",
      "https://res.cloudinary.com/dvuggm2if/image/upload/v1710398234/int.locales/5/qcspqaxohzbwzrv0y8tb.png",
      "https://res.cloudinary.com/dvuggm2if/image/upload/v1710398234/int.locales/5/qzikl2aglyq84hqxwb62.png",
      "https://res.cloudinary.com/dvuggm2if/image/upload/v1710398234/int.locales/5/joon9qjoatclvxanvc2p.png",
      "https://res.cloudinary.com/dvuggm2if/image/upload/v1710398234/int.locales/5/gsh5kaxnuh8cyfemw14e.png",
    ],
  },
  {
    description: "Tiendas ícono",
    company: "Entel S.A",
    location: "Santiago, Copiapó, Calama, Entre otros",
    area: "1.120 m2 aprox.",
    projectId: nanoid(),
    groupId: intLocalesID,
    img: [
      "https://res.cloudinary.com/dvuggm2if/image/upload/v1710398234/int.locales/6/b3ixgezjrmkfdrq9vvxk.png",
      "https://res.cloudinary.com/dvuggm2if/image/upload/v1710398234/int.locales/6/tyhwhbmkjoo9p7zji51t.png",
      "https://res.cloudinary.com/dvuggm2if/image/upload/v1710398234/int.locales/6/uqh6gnxnywgcuxw0oqwu.png",
      "https://res.cloudinary.com/dvuggm2if/image/upload/v1710398234/int.locales/6/ytyhhf5tmobetiypofch.png",
      "https://res.cloudinary.com/dvuggm2if/image/upload/v1710398234/int.locales/6/lytaahdxwzphdhtpalhb.png",
      "https://res.cloudinary.com/dvuggm2if/image/upload/v1710398234/int.locales/6/nx1ivka1ze0ieplgmhaw.png",
    ],
  },
  {
    description: "Habilitacion tienda",
    company: "Claro Chile",
    location: "Mall plaza mirador BioBio",
    area: "325 m2 aprox.",
    projectId: nanoid(),
    groupId: intLocalesID,
    img: [
      "https://res.cloudinary.com/dvuggm2if/image/upload/v1710398234/int.locales/7/cgrbemwo0znovxclq7ra.png",
      "https://res.cloudinary.com/dvuggm2if/image/upload/v1710398234/int.locales/7/ahgdpqmlhtr6nbkl7nlf.png",
      "https://res.cloudinary.com/dvuggm2if/image/upload/v1710398234/int.locales/7/rryhqyoevx4wqfgldrrp.png",
      "https://res.cloudinary.com/dvuggm2if/image/upload/v1710398234/int.locales/7/jkh0rjqsvfhre5ak7dpw.png",
    ],
  },
  {
    description: "Implementación nueva imagen 2018",
    company: "Claro Chile",
    location: "Locales a lo largo de todo Chile",
    area: "6.200 m2 aprox.",
    projectId: nanoid(),
    groupId: intLocalesID,
    img: [
      "https://res.cloudinary.com/dvuggm2if/image/upload/v1710398234/int.locales/8/fi9tuzix9pjekalk6ae3.png",
      "https://res.cloudinary.com/dvuggm2if/image/upload/v1710398234/int.locales/8/b9vuyaedralkquj3lzgw.png",
      "https://res.cloudinary.com/dvuggm2if/image/upload/v1710398234/int.locales/8/o0cloma6h3zb3cahlcix.png",
      "https://res.cloudinary.com/dvuggm2if/image/upload/v1710398234/int.locales/8/pmcv6zx3yt5ghe9haqzz.png",
    ],
  },
  {
    description: "Store of the future",
    company: "Telefónica",
    location: "Pedro Montt 1753-1799, Valparaíso",
    area: "456.41 m2",
    projectId: nanoid(),
    groupId: intLocalesID,
    img: [
      "https://res.cloudinary.com/dvuggm2if/image/upload/v1710398234/int.locales/9/szqijf5yzg9m1dgxohwc.png",
      "https://res.cloudinary.com/dvuggm2if/image/upload/v1710398234/int.locales/9/lz6vf1ndrue48tnd1l7u.png",
      "https://res.cloudinary.com/dvuggm2if/image/upload/v1710398234/int.locales/9/nztjszagjvfixsdctvl2.png",
      "https://res.cloudinary.com/dvuggm2if/image/upload/v1710398234/int.locales/9/efbzhf1dghmxy2o333d6.png",
      "https://res.cloudinary.com/dvuggm2if/image/upload/v1710398234/int.locales/9/dnhnhko9vnd8g069tvzd.png",
    ],
  },
  {
    description: "Implementacón nueva imagen | Habilitacion tiendas 2018",
    company: "Telefónica",
    location: "Locales a lo largo de todo Chile",
    area: "de 350 a 700 m2 aprox.",
    projectId: nanoid(),
    groupId: intLocalesID,
    img: [
      "https://res.cloudinary.com/dvuggm2if/image/upload/v1710398234/int.locales/10/apgilmtypipuosmce32s.png",
      "https://res.cloudinary.com/dvuggm2if/image/upload/v1710398234/int.locales/10/bvs3chtfg4wprqqskrm0.png",
      "https://res.cloudinary.com/dvuggm2if/image/upload/v1710398234/int.locales/10/ti7okapwuaba99gt9awi.png",
    ],
  },
  {
    description: "Store of the future",
    company: "Telefónica",
    location: "Mall Plaza Arica",
    area: "96.82 m2",
    projectId: nanoid(),
    groupId: intLocalesID,
    img: [
      "https://res.cloudinary.com/dvuggm2if/image/upload/v1710398234/int.locales/11/ht6dpgoxfxbmltzntwf9.png",
      "https://res.cloudinary.com/dvuggm2if/image/upload/v1710398234/int.locales/11/xaf6a9kch2p4kqlytnaw.png",
      "https://res.cloudinary.com/dvuggm2if/image/upload/v1710398234/int.locales/11/lejogcg4jg1l5j7ki8iu.png",
      "https://res.cloudinary.com/dvuggm2if/image/upload/v1710398234/int.locales/11/ucodfnbwya8cdoiae0av.png",
      "https://res.cloudinary.com/dvuggm2if/image/upload/v1710398234/int.locales/11/pbd66rnrm1aahtdoi4nn.png",
    ],
  },
]

export const intOficinasProjects = [
  {
    description: "Habilitacón nuevas oficinas administrativas",
    company: "Metbus S.A",
    location: "Moneda 1640, Santiago",
    area: "1.120 m2",
    area: "280 m2",
    projectId: nanoid(),
    groupId: intOfiID,
    img: [
      "https://res.cloudinary.com/dvuggm2if/image/upload/v1710398288/int.oficinas/0/ymhnrl58nnqppmgdaxnq.png",
      "https://res.cloudinary.com/dvuggm2if/image/upload/v1710398288/int.oficinas/0/zmfvn6qbtxejzrofpl86.png",
      "https://res.cloudinary.com/dvuggm2if/image/upload/v1710398288/int.oficinas/0/jokwpvugieuvayzoz4vw.png",
      "https://res.cloudinary.com/dvuggm2if/image/upload/v1710398288/int.oficinas/0/ickxohydk2edxnnufrzp.png",
    ],
  },
  {
    description: "Remodelación oficinas",
    company: "Entel S.A",
    location: "Amunátegui 20, Santiago",
    area: "900 m2",
    projectId: nanoid(),
    groupId: intOfiID,
    img: [
      "https://res.cloudinary.com/dvuggm2if/image/upload/v1710398288/int.oficinas/1/sxr4367cbfusgkgayqoj.png",
      "https://res.cloudinary.com/dvuggm2if/image/upload/v1710398288/int.oficinas/1/bwpto44cf5eu14v80vxq.png",
      "https://res.cloudinary.com/dvuggm2if/image/upload/v1710398288/int.oficinas/1/a7i5ftuvf9sdovmkrf8d.png",
      "https://res.cloudinary.com/dvuggm2if/image/upload/v1710398288/int.oficinas/1/eg05k6kewd0mfxifksvc.png",
      "https://res.cloudinary.com/dvuggm2if/image/upload/v1710398288/int.oficinas/1/eeqlk6w10ne7hh2ac1rh.png",
      "https://res.cloudinary.com/dvuggm2if/image/upload/v1710398288/int.oficinas/1/qwpy5ivirc38dtdlqzz5.png",
    ],
  },
  {
    description: "Habilitación CIC | Laboratorio",
    company: "Entel S.A",
    location: "Capitan Orellana 2482, Ñuñoa",
    area: "240 m2",
    projectId: nanoid(),
    groupId: intOfiID,
    img: [
      "https://res.cloudinary.com/dvuggm2if/image/upload/v1710398288/int.oficinas/2/vautaqw8mua9ee6vylro.png",
      "https://res.cloudinary.com/dvuggm2if/image/upload/v1710398288/int.oficinas/2/qj0qsjihmrkbc5r64ypc.png",
      "https://res.cloudinary.com/dvuggm2if/image/upload/v1710398288/int.oficinas/2/pbbzcdvj10zolrqfjwvc.png",
      "https://res.cloudinary.com/dvuggm2if/image/upload/v1710398288/int.oficinas/2/h6nkv6i1rrgyikvjxhyd.png",
    ],
  },
  {
    description: "Oficinas auditoria",
    company: "KPMG Auditores Consultores",
    location: "Av. Isidora Goyenechea 3220, Las Condes",
    area: "1.100 m2",
    projectId: nanoid(),
    groupId: intOfiID,
    img: [
      "https://res.cloudinary.com/dvuggm2if/image/upload/v1710398288/int.oficinas/3/edfankcfzlsvkoo8bc1j.png",
      "https://res.cloudinary.com/dvuggm2if/image/upload/v1710398288/int.oficinas/3/vztdxx0pk7utktj6syec.png",
      "https://res.cloudinary.com/dvuggm2if/image/upload/v1710398288/int.oficinas/3/hehpbbf6avei1vr5qrhz.png",
      "https://res.cloudinary.com/dvuggm2if/image/upload/v1710398288/int.oficinas/3/bytwkr9goxv3gdgqso0n.png",
    ],
  },
  {
    description: "Comedor para personal",
    company: "KPMG Auditores Consultores",
    location: "Av. Isidora Goyenechea 3220, Las Condes",
    area: "175 m2",
    projectId: nanoid(),
    groupId: intOfiID,
    img: [
      "https://res.cloudinary.com/dvuggm2if/image/upload/v1710398288/int.oficinas/4/guinx1hw0494erqq4rzo.png",
      "https://res.cloudinary.com/dvuggm2if/image/upload/v1710398288/int.oficinas/4/mdaw8g0dcdefzpbujlvh.png",
      "https://res.cloudinary.com/dvuggm2if/image/upload/v1710398288/int.oficinas/4/bfyevgt1yl8o2b8t69gn.png",
      "https://res.cloudinary.com/dvuggm2if/image/upload/v1710398288/int.oficinas/4/zkpehkmf3m7jxvd1ijuj.png",
      "https://res.cloudinary.com/dvuggm2if/image/upload/v1710398288/int.oficinas/4/y6frqcajiyuhyaa46ctk.png",
    ],
  },
  {
    description: "Habilitación nuevas oficinas",
    company: "AVA Montajes Industriales",
    location: "Autopista Concepción Talcahuano N°8696, piso 7, Hualpén",
    area: "280 m2",
    projectId: nanoid(),
    groupId: intOfiID,
    img: [
      "https://res.cloudinary.com/dvuggm2if/image/upload/v1710398288/int.oficinas/5/sgbiaxqpl9jzbf6lbdem.png",
      "https://res.cloudinary.com/dvuggm2if/image/upload/v1710398288/int.oficinas/5/cfhfimb3izcf2q9een0j.png",
      "https://res.cloudinary.com/dvuggm2if/image/upload/v1710398288/int.oficinas/5/tipuzpkptgzlkdmyvd54.png",
      "https://res.cloudinary.com/dvuggm2if/image/upload/v1710398288/int.oficinas/5/cg9pcd8v2rrlh11ipwop.png",
    ],
  },
  {
    description: "Habilitación Contact Center",
    company: "Coopeuch",
    location: "Av. L.B. O'higgins 301",
    area: "964 m2",
    projectId: nanoid(),
    groupId: intOfiID,
    img: [
      "https://res.cloudinary.com/dvuggm2if/image/upload/v1710398288/int.oficinas/6/wx4i0nejtqneuvorqxs8.png",
      "https://res.cloudinary.com/dvuggm2if/image/upload/v1710398288/int.oficinas/6/f7c0l75ysuekkrmoybjr.png",
      "https://res.cloudinary.com/dvuggm2if/image/upload/v1710398288/int.oficinas/6/r2nfhyitjtxmzc7uwopd.png",
      "https://res.cloudinary.com/dvuggm2if/image/upload/v1710398288/int.oficinas/6/mvazgd5c6ahf3hawe8qb.png",
      "https://res.cloudinary.com/dvuggm2if/image/upload/v1710398288/int.oficinas/6/n8aplkeg6qp1y0sn61jy.png",
      "https://res.cloudinary.com/dvuggm2if/image/upload/v1710398288/int.oficinas/6/hpdn0vad4jast9mmig29.png",
    ],
  },
  {
    description: "Optimización de espacios",
    company: "Telefónica",
    location: "Edificio corpotativo Telefónica, Providencia",
    area: "600 m2",
    projectId: nanoid(),
    groupId: intOfiID,
    img: [
      "https://res.cloudinary.com/dvuggm2if/image/upload/v1710398288/int.oficinas/7/odh6ar0sfygxeor799fk.png",
      "https://res.cloudinary.com/dvuggm2if/image/upload/v1710398288/int.oficinas/7/wfpdrrx8tzwmdypimrfb.png",
      "https://res.cloudinary.com/dvuggm2if/image/upload/v1710398288/int.oficinas/7/pmcrujic8v0zrmlbekxq.png",
      "https://res.cloudinary.com/dvuggm2if/image/upload/v1710398288/int.oficinas/7/ensuq1ktojebtccjjuhv.png",
    ],
  },
  {
    description: "Oficinas Santiago Chile",
    company: "I+D",
    location: "Av. Manuel Montt 1404, Providencia",
    area: "350 m2",
    projectId: nanoid(),
    groupId: intOfiID,
    img: [
      "https://res.cloudinary.com/dvuggm2if/image/upload/v1710398288/int.oficinas/8/wkmsdixrndy6dk9ssvzg.png",
      "https://res.cloudinary.com/dvuggm2if/image/upload/v1710398288/int.oficinas/8/zedpyxnhtbqzmtodpxpp.png",
      "https://res.cloudinary.com/dvuggm2if/image/upload/v1710398288/int.oficinas/8/nrtm9vu6f0ueqmgpfwy5.png",
      "https://res.cloudinary.com/dvuggm2if/image/upload/v1710398288/int.oficinas/8/xs9mwdv2k272xoka4vh8.png",
    ],
  },
];

export const arquitectutaIndProjects = [
  {
    description: "Informe bodega de gas y combustibles",
    company: "Latam airlines",
    location: "Base mantenimiento latam en aeropuerto C.A.M.B",
    area: "244 m2",
    projectId: nanoid(),
    groupId: arqIndID,
    img: [
      "https://res.cloudinary.com/dvuggm2if/image/upload/v1710398198/industrial/0/zjsvemkctzwferoacr2b.png",
      "https://res.cloudinary.com/dvuggm2if/image/upload/v1710398198/industrial/0/tank4bdv9kjl7m7sz3yf.png",
      "https://res.cloudinary.com/dvuggm2if/image/upload/v1710398198/industrial/0/mlb8lhlvxouppzvfv4mv.png",
    ],
  },
  {
    description:
      "Ampliación y remodelación bodega de sustancias peligrosas. gases y combustibles",
    company: "Latam airlines",
    location: "Base mantenimiento latam en aeropuerto C.A.M.B",
    area: "244 + 125 m2",
    projectId: nanoid(),
    groupId: arqIndID,
    img: [
      "https://res.cloudinary.com/dvuggm2if/image/upload/v1710398198/industrial/1/s2zamq74bgfe27j8b8ln.png",
      "https://res.cloudinary.com/dvuggm2if/image/upload/v1710398198/industrial/1/icbx0ftxpuft4wxrbto3.png",
      "https://res.cloudinary.com/dvuggm2if/image/upload/v1710398198/industrial/1/nul0ddwkh5cie6q3izry.png",
      "https://res.cloudinary.com/dvuggm2if/image/upload/v1710398198/industrial/1/hnrkoh8lqylu0yvu9d76.png",
      "https://res.cloudinary.com/dvuggm2if/image/upload/v1710398198/industrial/1/vabehtuwuzbnvmknpfgg.png",
      "https://res.cloudinary.com/dvuggm2if/image/upload/v1710398198/industrial/1/skahyrdzndqbw7chzjbc.png",
    ],
  },
  {
    description: "Ampliación almacén proviciones",
    company: "Latam airlines",
    location: "Base mantenimiento latam en aeropuerto C.A.M.B",
    area: "280 m2 - 8.0 m altura libre interior",
    projectId: nanoid(),
    groupId: arqIndID,
    img: [
      "https://res.cloudinary.com/dvuggm2if/image/upload/v1710398198/industrial/2/xozxjpizv3trmb1ytzd1.png",
      "https://res.cloudinary.com/dvuggm2if/image/upload/v1710398198/industrial/2/qwaumeexevngezn9ntxr.png",
      "https://res.cloudinary.com/dvuggm2if/image/upload/v1710398198/industrial/2/sybqgldtdmdftkacaf8q.png",
      "https://res.cloudinary.com/dvuggm2if/image/upload/v1710398198/industrial/2/e8fkzquuzlrv77x6ih9r.png",
      "https://res.cloudinary.com/dvuggm2if/image/upload/v1710398198/industrial/2/tr284cqgxkxqw5iwy0bg.png",
      "https://res.cloudinary.com/dvuggm2if/image/upload/v1710398198/industrial/2/ab0mppiqpd3n9qm3gebw.png",
    ],
  },
  {
    description: "Talleres y bodegas",
    company: "Dirección general de aeronáutica civil",
    location: "Aeropuerto A. Merino Benitez",
    area: "1.280 m2",
    projectId: nanoid(),
    groupId: arqIndID,
    img: [
      "https://res.cloudinary.com/dvuggm2if/image/upload/v1710398198/industrial/3/hwsdeeuz6ogjdyj7o30p.png",
      "https://res.cloudinary.com/dvuggm2if/image/upload/v1710398198/industrial/3/te5ae5fldoengnpmkzbd.png",
      "https://res.cloudinary.com/dvuggm2if/image/upload/v1710398198/industrial/3/a5bgfbh7jnprp8tros0c.png",
      "https://res.cloudinary.com/dvuggm2if/image/upload/v1710398198/industrial/3/j6i4ypitl4crjdzk0yyt.png",
      "https://res.cloudinary.com/dvuggm2if/image/upload/v1710398198/industrial/3/qkupojttr2nhwvqsvr8d.png",
      "https://res.cloudinary.com/dvuggm2if/image/upload/v1710398198/industrial/3/wxa8guscbae9wzglnugu.png",
    ],
  },
  {
    description: "Edificio modular para proveedores",
    company: "Latam airlines",
    location: "Base mantenimiento latam en aeropuerto C.A.M.B",
    area: "480 m2",
    projectId: nanoid(),
    groupId: arqIndID,
    img: [
      "https://res.cloudinary.com/dvuggm2if/image/upload/v1710398198/industrial/4/exupwidzyj9cvpd6jfxq.png",
      "https://res.cloudinary.com/dvuggm2if/image/upload/v1710398198/industrial/4/pzcaq0ccpwuknm90fs08.png",
      "https://res.cloudinary.com/dvuggm2if/image/upload/v1710398198/industrial/4/pviyit3b97wschliaunf.png",
      "https://res.cloudinary.com/dvuggm2if/image/upload/v1710398198/industrial/4/xpu2eyoorwsdyl4ymwhi.png",
      "https://res.cloudinary.com/dvuggm2if/image/upload/v1710398198/industrial/4/n4hddxm93sm9rdjjezas.png",
    ],
  },
  {
    description: "Cubierta acceso y remodelacion areas verdes",
    company: "Latam airlines",
    location: "Base mantenimiento latam en aeropuerto C.A.M.B",
    area: "2.200 m2",
    projectId: nanoid(),
    groupId: arqIndID,
    img: [
      "https://res.cloudinary.com/dvuggm2if/image/upload/v1710398198/industrial/5/gtefnqbio3edopsbspzk.png",
      "https://res.cloudinary.com/dvuggm2if/image/upload/v1710398198/industrial/5/lo9eio0pui9b4hynecfn.png",
      "https://res.cloudinary.com/dvuggm2if/image/upload/v1710398198/industrial/5/zhgeuwsk2gbfxngxdto0.png",
    ],
  },
  {
    description: "Exhibición motor trent | 1000 Roll Roys",
    company: "Latam airlines",
    location: "Base mantenimiento latam en aeropuerto C.A.M.B",
    area: "100 m2",
    projectId: nanoid(),
    groupId: arqIndID,
    img: [
      "https://res.cloudinary.com/dvuggm2if/image/upload/v1710398198/industrial/6/ve87hpucigwlspxbk5ea.png",
      "https://res.cloudinary.com/dvuggm2if/image/upload/v1710398198/industrial/6/mnnvu7fvbdr6afl16qct.png",
      "https://res.cloudinary.com/dvuggm2if/image/upload/v1710398198/industrial/6/pxvqn0wkzrzcfhvgfdpf.png",
      "https://res.cloudinary.com/dvuggm2if/image/upload/v1710398198/industrial/6/fafnuhooghgtlxfhwvkf.png",
      "https://res.cloudinary.com/dvuggm2if/image/upload/v1710398198/industrial/6/ezecc8bfwbaryixhrm0y.png",
    ],
  },
  {
    description:
      "Edificios apoyo personal y subestación eléctrica en plataforma crecimiento norte",
    company: "Lan airlines",
    location: "Base mantenimiento lan en aeropuerto C.A.M.B",
    area: "280 m2",
    projectId: nanoid(),
    groupId: arqIndID,
    img: [
      "https://res.cloudinary.com/dvuggm2if/image/upload/v1710398198/industrial/7/tunffounctlscikpb8lz.png",
      "https://res.cloudinary.com/dvuggm2if/image/upload/v1710398198/industrial/7/qvjzo6fuuihbpxx9m2x3.png",
      "https://res.cloudinary.com/dvuggm2if/image/upload/v1710398198/industrial/7/rex4kl3s8km8arjllsiv.png",
      "https://res.cloudinary.com/dvuggm2if/image/upload/v1710398198/industrial/7/uxi5zgdxyc0joqqciqqv.png",
    ],
  },
  {
    description: "Reja contensión acceso Kennedy",
    company: "Parque Arauco S.A",
    location: "Av. Kennedy 5413, Las Condes",
    area: "280 m2",
    projectId: nanoid(),
    groupId: arqIndID,
    img: [
      "https://res.cloudinary.com/dvuggm2if/image/upload/v1710398198/industrial/8/rp8dv3nbje9gt35qfp39.png",
      "https://res.cloudinary.com/dvuggm2if/image/upload/v1710398198/industrial/8/aiaiagrisudynaomjnfg.png",
    ],
  },
];

export const disenoMobProjects = [
  {
    description: "Diseño y ejecución de mobiliario especial",
    company: "Latam travel",
    location: "-",
    area: "-",
    projectId: nanoid(),
    groupId: mobDisID,
    img: [
      "https://res.cloudinary.com/dvuggm2if/image/upload/v1710398179/arq.int/0/v7gvmppja2ziaunlboj3.png",
      "https://res.cloudinary.com/dvuggm2if/image/upload/v1710398179/arq.int/0/et5rihe07fvmwssqntdb.png",
      "https://res.cloudinary.com/dvuggm2if/image/upload/v1710398179/arq.int/0/j01lnhvsluete5p9gqsi.png",
      "https://res.cloudinary.com/dvuggm2if/image/upload/v1710398179/arq.int/0/lewsxxycd9l55472pttk.png",
    ],
  },
  {
    description: "Diseño y ejecución de mobiliario especial",
    company: "Latam travel",
    location: "",
    area: "-",
    projectId: nanoid(),
    groupId: mobDisID,
    img: [
      "https://res.cloudinary.com/dvuggm2if/image/upload/v1710398179/arq.int/1/fyzqpt0yp36ljkzmlfpe.png",
      "https://res.cloudinary.com/dvuggm2if/image/upload/v1710398179/arq.int/1/fygqexakysjcbocfqo8s.png",
      "https://res.cloudinary.com/dvuggm2if/image/upload/v1710398179/arq.int/1/wugxt603rkrpb508xxgr.png",
      "https://res.cloudinary.com/dvuggm2if/image/upload/v1710398179/arq.int/1/rfyaipwg5eqohojo9uvr.png",
      "https://res.cloudinary.com/dvuggm2if/image/upload/v1710398179/arq.int/1/preopzjmtpe09rpghfnw.png",
      "https://res.cloudinary.com/dvuggm2if/image/upload/v1710398179/arq.int/1/tqcbzg4ltrvr0m2ejkkv.png",
    ],
  },
  {
    description: "Kiosko urbano | AT. service de SK",
    company: "Latam airlines",
    location: "Instalaciones Lan en base MTTO, Edificio Vespucio Sur",
    area: "16 m2",
    projectId: nanoid(),
    groupId: mobDisID,
    img: [
      "https://res.cloudinary.com/dvuggm2if/image/upload/v1710398179/arq.int/2/yfxghbytdw1pzaxpq4gc.png",
      "https://res.cloudinary.com/dvuggm2if/image/upload/v1710398179/arq.int/2/n9sqdafjkicngr5dpw2d.png",
      "https://res.cloudinary.com/dvuggm2if/image/upload/v1710398179/arq.int/2/hkxgvni5hel0qn8oalvb.png",
      "https://res.cloudinary.com/dvuggm2if/image/upload/v1710398179/arq.int/2/nbtbw6xiehciiu7so47o.png",
    ],
  },
];

export const allProjects =  [
    ...intLocalesProjects,
    ...intOficinasProjects,
    ...arquitectutaIndProjects,
    ...disenoMobProjects,
  ];

